name: Test Create Release
permissions:
  contents: write

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: Deploy CGCA Web
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout new code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
#          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "C:/deployment-stage/cgca-release.txt"
          create: true
          generateReleaseNotes: true
      
